url: "cotruths.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Constellation of Truths" # the name of your site, e.g. ACME Corp.
description: "A SSHRC IDG funded project"
