menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'events', url: '/events'}

people:
- {name: 'Emma Swan, PhD', title: 'Researcher', department: 'Political Science', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Maria Sigridur Finnsdottir, PhD', title: 'Humanities & Social Sciences Specialist', department: 'Digital Research Services', institution: 'University of Alberta', email: 'mariafin@uvic.ca', image: 'assets/img/maria.jpg', url: 'maria'}
- {name: 'Jules Soupault', title: 'Doctoral Fellow, Borders in Globalization', department: 'School of Public Administration', institution: 'University of Victoria', email: 'hello@university.edu', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

events:
- {name: 'Constellation of Truths Spring 2025 Workshop', description: 'The project members hosted an interdisciplinary conference on border politics at the University of Victoria in April 2025.', url: '/events/cot_workshop_2025.md', img: './assets/img/network.png'}